[build]
  command = "npm install --legacy-peer-deps; npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NPM_FLAGS = "--legacy-peer-deps"

  [[redirects]]
  from = "www.sang-logium.com/*"
  to = "https://sang-logium.com/:splat"
  status = 301
  force = true