[build]
  command = "npm install --legacy-peer-deps; npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NPM_FLAGS = "--legacy-peer-deps"

# Add proper cache headers
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Proper Next.js fallback handling is managed by @netlify/plugin-nextjs
# Remove SPA fallback which conflicts with Next.js asset handling

